apiVersion: v1
kind: Secret
data:
  SecureString: abcdefg123
metadata:
  annotations:
    aws-ssm/aws-param-key: aws/ssm
    aws-ssm/aws-param-name: parameterStoreHere
    aws-ssm/aws-param-type: SecureString
  name: dumbledore-test
  namespace: dumbledore
type: Opaque