{{ if empty .Values.deployment.customServiceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.customNamespace | default "dumbledore" }}
{{ end }}