apiVersion: v1
kind: Secret
data:
  SecureString: ""
metadata:
  annotations:
    aws-ssm/aws-param-key: aws/ssm
    aws-ssm/aws-param-name: parameterStoreHere
    aws-ssm/aws-param-type: SecureString
  name: work
  namespace: default
type: Opaque